[node-utils] tsconfig.json - don't include vite.config.ts
This is an attempt to get rid of what seems to be a spurious build
error reporting that:

```
vite v6.3.3 building SSR bundle for production...
vite.config.ts:4:35 - error TS7016: Could not find a declaration file for module '@mykomap/common'. '/home/nick/i/gitworking/DCC/mykomap-monolith/libs/common/dist/common.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/mykomap__common` if it exists or add a new declaration (.d.ts) file containing `declare module '@mykomap/common';`

4 import { ReadonlyBuildInfo } from "@mykomap/common";
                                    ~~~~~~~~~~~~~~~~~

```

This may be spurious, like the issue addressed by the previous commit.

In any case, this gets rid of the error - not sure if it will cause
problems elsewhere, let's wait and see.